# Generated by Django 4.1.2 on 2023-10-22 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='user',
        ),
    ]
