# Generated by Django 4.1.2 on 2023-10-25 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarks', '0002_remove_session_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='uniqueAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_auth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='unique_auth',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bookmarks.uniqueauth'),
            preserve_default=False,
        ),
    ]
