# Generated by Django 4.1.2 on 2023-10-29 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarks', '0004_session_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueauth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unique_auth', to=settings.AUTH_USER_MODEL),
        ),
    ]
