# Generated by Django 4.1.2 on 2023-11-08 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0005_alter_uniqueauth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='tabs',
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('logo', models.URLField(max_length=2048)),
                ('title', models.CharField(max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookmarks.session')),
            ],
        ),
    ]
