# Generated by Django 4.1.2 on 2023-11-14 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0006_remove_session_tabs_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='bookmarks.session'),
        ),
    ]
