# Generated by Django 4.1.2 on 2023-11-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0008_uniqueauth_user_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueauth',
            name='value',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
